CREATE TABLE IF NOT EXISTS wecom_integration (
  id BIGINT PRIMARY KEY,
  corp_id VARCHAR(64) NOT NULL,
  agent_id VARCHAR(32) NOT NULL,
  encrypted_secret TEXT NOT NULL,
  sso_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  message_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
