export const MANUAL_SOURCE_LABEL = '人工录入'
export const CRM_SOURCE_LABEL = 'CRM创建'
export const LEGACY_CRM_SOURCE_LABEL = 'CRM 创建'
export const EXTERNAL_PLATFORM_SOURCE_LABEL = '第三方平台'

export const SOURCE_PLATFORM_OPTIONS = [MANUAL_SOURCE_LABEL, CRM_SOURCE_LABEL, EXTERNAL_PLATFORM_SOURCE_LABEL]
