-- Input: migration-mysql/V1109__add_resource_permissions_to_bid_project_leader.sql
-- Output: rollback note for mysql environments; original custom menu permission order is not stored.
-- Pos: Flyway rollback documentation for 西域数智化投标管理平台.
-- 维护声明: source migration changes must update this rollback script in the same branch.

-- Data rollback required for UPDATE roles; original values are not stored in migration history.
-- If manual rollback is required, remove the three tokens (resource, resource-account, resource-ca)
-- from bid-projectLeader after confirming they were introduced by V1109.
-- 示例（MySQL 8.0 REGEXP_REPLACE）：
-- UPDATE roles
-- SET menu_permissions = TRIM(BOTH ',' FROM REGEXP_REPLACE(CONCAT(',', menu_permissions, ','), ',(resource|resource-account|resource-ca),', ','))
-- WHERE code = 'bid-projectLeader';
