-- Input: migration-mysql/B73__full_schema_baseline.sql
-- Output: rollback script for mysql environments; review data-loss comments before production use.
-- Pos: Flyway historical down migration coverage for 西域数智化投标管理平台.
-- 维护声明: source migration changes must update this rollback script in the same branch.

-- Data rollback required for INSERT INTO roles; verify seed rows before deleting.
ALTER TABLE users DROP FOREIGN KEY FKp56c1712k691lhsyewcssf40f;
ALTER TABLE template_versions DROP FOREIGN KEY FK9gy13bl9n6n45605pb93htaxx;
ALTER TABLE template_use_records DROP FOREIGN KEY FK3ia252hoqeioht3vqvxqgc05s;
ALTER TABLE template_tags DROP FOREIGN KEY FKb690bd7lptenw09h0u23iwila;
ALTER TABLE template_download_records DROP FOREIGN KEY FK6hyrt9u60k493mra3vqtg13b5;
ALTER TABLE refresh_sessions DROP FOREIGN KEY FK9ndfh1op1iy3xuqyi6gxkseg0;
ALTER TABLE project_team_members DROP FOREIGN KEY FKrplt19ljycvlrk9fy72yep75e;
ALTER TABLE project_group_role_access DROP FOREIGN KEY FKao9yo4xloylqq0iphrna0rm03;
ALTER TABLE project_group_projects DROP FOREIGN KEY FKq6hhbhmbsib75deebi5e5tth4;
ALTER TABLE project_group_members DROP FOREIGN KEY FKr0fmvpgokjn2mpptv7qat6shh;
ALTER TABLE password_reset_tokens DROP FOREIGN KEY FKk3ndxg5xp6v7wd4gjyusp15gq;
ALTER TABLE email_verification_tokens DROP FOREIGN KEY FKi1c4mmamlb8keqt74k4lrtwhc;
ALTER TABLE case_technologies DROP FOREIGN KEY FKsgesjrn67pmbsbjww06appe3g;
ALTER TABLE case_tags DROP FOREIGN KEY FK5lux2odxtf0cmef0shrqakd07;
ALTER TABLE case_success_factors DROP FOREIGN KEY FKhc1yltykgesh29adh8c1rveox;
ALTER TABLE case_lessons_learned DROP FOREIGN KEY FK86g2td5ti22l2yhsomuj0huuv;
ALTER TABLE case_highlights DROP FOREIGN KEY FKbv3me1wdrtmxs3q3kt94flu0k;
ALTER TABLE case_attachment_names DROP FOREIGN KEY FKei1fv1mtwa9xb5ufcqhty2ix4;
ALTER TABLE users DROP INDEX UK_r43af9ap4edm43mmtq01oddj6;
ALTER TABLE users DROP INDEX UK_6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE tenders DROP INDEX UK_i07ipdk97nopwineqty0816ml;
DROP INDEX idx_tender_ai_score ON tenders;
DROP INDEX idx_tender_deadline ON tenders;
DROP INDEX idx_tender_source ON tenders;
DROP INDEX idx_tender_status ON tenders;
ALTER TABLE task_deliverables DROP INDEX UK_th3pfdl5atat5ggp5w92f03x;
DROP INDEX idx_task_del_type ON task_deliverables;
DROP INDEX idx_task_del_task_id ON task_deliverables;
ALTER TABLE system_settings DROP INDEX UK_cv6i1lu658ukkwnk4cuvj0ow0;
DROP INDEX idx_score_analysis_risk ON score_analyses;
DROP INDEX idx_score_analysis_date ON score_analyses;
DROP INDEX idx_score_analysis_project ON score_analyses;
ALTER TABLE roles DROP INDEX UK_ch1113horj4qr56f91omojv8;
DROP INDEX idx_roi_analysis_date ON roi_analyses;
DROP INDEX idx_roi_project ON roi_analyses;
ALTER TABLE refresh_sessions DROP INDEX UK_8dm8ib9n3bwiy2fjx1411w08d;
DROP INDEX idx_project_dates ON projects;
DROP INDEX idx_project_tender ON projects;
DROP INDEX idx_project_manager ON projects;
DROP INDEX idx_project_status ON projects;
ALTER TABLE project_share_links DROP INDEX UK_b8ltlmqyet5wpswegfyihvluk;
DROP INDEX idx_score_preview_tender ON project_score_previews;
DROP INDEX idx_score_preview_project ON project_score_previews;
ALTER TABLE project_groups DROP INDEX UK_n1sq2ky02kvteuxw8r5oo9q7e;
DROP INDEX idx_project_group_manager ON project_groups;
ALTER TABLE platform_accounts DROP INDEX UK_14e3v80s7wywpcjk713rniikd;
DROP INDEX idx_platform_borrowed_by ON platform_accounts;
DROP INDEX idx_platform_type ON platform_accounts;
DROP INDEX idx_platform_status ON platform_accounts;
DROP INDEX idx_platform_username ON platform_accounts;
ALTER TABLE password_reset_tokens DROP INDEX UK_71lqwbwtklmljk3qlsugr1mig;
DROP INDEX idx_password_reset_expires ON password_reset_tokens;
DROP INDEX idx_password_reset_user ON password_reset_tokens;
DROP INDEX idx_password_reset_token ON password_reset_tokens;
ALTER TABLE historical_project_snapshots DROP INDEX UK_c3q79d6kv4gwat3my93qyaewn;
DROP INDEX idx_history_snapshot_export ON historical_project_snapshots;
DROP INDEX idx_history_snapshot_archive ON historical_project_snapshots;
DROP INDEX idx_history_snapshot_project ON historical_project_snapshots;
DROP INDEX idx_fee_project_status ON fees;
DROP INDEX idx_fee_type ON fees;
DROP INDEX idx_fee_status ON fees;
DROP INDEX idx_fee_project ON fees;
DROP INDEX idx_export_status ON export_tasks;
DROP INDEX idx_export_user ON export_tasks;
ALTER TABLE email_verification_tokens DROP INDEX UK_ewmvysc7e9y6uy7og2c21axa9;
DROP INDEX idx_email_verify_user ON email_verification_tokens;
DROP INDEX idx_email_verify_token ON email_verification_tokens;
DROP INDEX idx_project_current ON document_versions;
DROP INDEX idx_document_id ON document_versions;
DROP INDEX idx_document_version_project_id ON document_versions;
ALTER TABLE document_locks DROP INDEX UK_qapdeuoy23y462v3ig6kyy9yb;
DROP INDEX idx_document_export_structure ON document_exports;
DROP INDEX idx_document_export_project ON document_exports;
ALTER TABLE document_export_files DROP INDEX UK_2yxrqfdw37mkbsjr8cp6sqek8;
DROP INDEX idx_document_export_file_export ON document_export_files;
ALTER TABLE document_assignments DROP INDEX UK_px8r2avjc26q8jot3arnlm7jt;
DROP INDEX idx_assembly_project_template ON document_assemblies;
DROP INDEX idx_assembly_template ON document_assemblies;
DROP INDEX idx_assembly_project ON document_assemblies;
DROP INDEX idx_document_archive_structure ON document_archive_records;
DROP INDEX idx_document_archive_project ON document_archive_records;
DROP INDEX idx_dimension_name ON dimension_scores;
DROP INDEX idx_dimension_analysis ON dimension_scores;
DROP INDEX idx_cp_opportunity_score ON customer_predictions;
DROP INDEX idx_cp_status ON customer_predictions;
DROP INDEX idx_cp_purchaser_hash ON customer_predictions;
DROP INDEX idx_rule_enabled ON compliance_rules;
DROP INDEX idx_rule_type ON compliance_rules;
DROP INDEX idx_result_checked_at ON compliance_check_results;
DROP INDEX idx_result_status ON compliance_check_results;
DROP INDEX idx_result_tender ON compliance_check_results;
DROP INDEX idx_result_project ON compliance_check_results;
DROP INDEX idx_competitor_industry ON competitors;
DROP INDEX idx_competitor_name ON competitors;
DROP INDEX idx_analysis_project_competitor ON competition_analyses;
DROP INDEX idx_analysis_date ON competition_analyses;
DROP INDEX idx_analysis_competitor ON competition_analyses;
DROP INDEX idx_analysis_project ON competition_analyses;
DROP INDEX idx_comment_thread_deleted ON comments;
DROP INDEX idx_comment_deleted ON comments;
DROP INDEX idx_comment_parent ON comments;
DROP INDEX idx_comment_user ON comments;
DROP INDEX idx_comment_thread ON comments;
DROP INDEX idx_thread_project_status ON collaboration_threads;
DROP INDEX idx_thread_status ON collaboration_threads;
DROP INDEX idx_thread_project ON collaboration_threads;
ALTER TABLE case_share_records DROP INDEX UK_p7mn0hbtj3xf60qa6uvdmvu7;
DROP INDEX idx_date_range ON calendar_events;
DROP INDEX idx_urgent ON calendar_events;
DROP INDEX idx_calendar_project_id ON calendar_events;
DROP INDEX idx_event_type ON calendar_events;
DROP INDEX idx_event_date ON calendar_events;
DROP INDEX idx_bid_result_sync_type ON bid_result_sync_logs;
DROP INDEX idx_bid_result_reminder_status ON bid_result_reminders;
DROP INDEX idx_bid_result_reminder_project ON bid_result_reminders;
DROP INDEX idx_bid_result_fetch_tender ON bid_result_fetch_results;
DROP INDEX idx_bid_result_fetch_project ON bid_result_fetch_results;
DROP INDEX idx_bid_result_fetch_status ON bid_result_fetch_results;
ALTER TABLE bar_site_sops DROP INDEX UK_i8je16cbyau9qsiu4qoa5fx4d;
DROP INDEX idx_audit_entity ON audit_logs;
DROP INDEX idx_audit_timestamp ON audit_logs;
DROP INDEX idx_audit_action ON audit_logs;
DROP INDEX idx_audit_user ON audit_logs;
DROP INDEX idx_template_created_by ON assembly_templates;
DROP INDEX idx_template_category ON assembly_templates;
DROP INDEX idx_approval_type ON approval_requests;
DROP INDEX idx_created_at ON approval_requests;
DROP INDEX idx_requester_id ON approval_requests;
DROP INDEX idx_status ON approval_requests;
DROP INDEX idx_project_id ON approval_requests;
DROP INDEX idx_actor_id ON approval_actions;
DROP INDEX idx_action_time ON approval_actions;
DROP INDEX idx_approval_request_id ON approval_actions;
DROP INDEX idx_ai_result_job ON ai_analysis_results;
DROP INDEX idx_ai_result_project ON ai_analysis_results;
DROP INDEX idx_ai_result_tender ON ai_analysis_results;
DROP INDEX idx_ai_job_status ON ai_analysis_jobs;
DROP INDEX idx_ai_job_target ON ai_analysis_jobs;
ALTER TABLE accounts DROP INDEX UK_qtv290mh55xhggmpwosf5ag0v;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenders;
DROP TABLE IF EXISTS tender_assignment_records;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS template_versions;
DROP TABLE IF EXISTS template_use_records;
DROP TABLE IF EXISTS template_tags;
DROP TABLE IF EXISTS template_download_records;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS task_deliverables;
DROP TABLE IF EXISTS system_settings;
DROP TABLE IF EXISTS score_analyses;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS roi_analyses;
DROP TABLE IF EXISTS refresh_sessions;
DROP TABLE IF EXISTS qualifications;
DROP TABLE IF EXISTS qualification_loan_records;
DROP TABLE IF EXISTS qualification_attachments;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS project_team_members;
DROP TABLE IF EXISTS project_share_links;
DROP TABLE IF EXISTS project_score_previews;
DROP TABLE IF EXISTS project_score_drafts;
DROP TABLE IF EXISTS project_reminders;
DROP TABLE IF EXISTS project_quality_issues;
DROP TABLE IF EXISTS project_quality_checks;
DROP TABLE IF EXISTS project_groups;
DROP TABLE IF EXISTS project_group_role_access;
DROP TABLE IF EXISTS project_group_projects;
DROP TABLE IF EXISTS project_group_members;
DROP TABLE IF EXISTS project_documents;
DROP TABLE IF EXISTS platform_accounts;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS historical_project_snapshots;
DROP TABLE IF EXISTS fees;
DROP TABLE IF EXISTS export_tasks;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS expense_payment_records;
DROP TABLE IF EXISTS expense_approval_records;
DROP TABLE IF EXISTS email_verification_tokens;
DROP TABLE IF EXISTS document_versions;
DROP TABLE IF EXISTS document_structures;
DROP TABLE IF EXISTS document_sections;
DROP TABLE IF EXISTS document_reminders;
DROP TABLE IF EXISTS document_locks;
DROP TABLE IF EXISTS document_exports;
DROP TABLE IF EXISTS document_export_files;
DROP TABLE IF EXISTS document_assignments;
DROP TABLE IF EXISTS document_assemblies;
DROP TABLE IF EXISTS document_archive_records;
DROP TABLE IF EXISTS dimension_scores;
DROP TABLE IF EXISTS customer_predictions;
DROP TABLE IF EXISTS compliance_rules;
DROP TABLE IF EXISTS compliance_check_results;
DROP TABLE IF EXISTS competitors;
DROP TABLE IF EXISTS competitor_win_records;
DROP TABLE IF EXISTS competition_analyses;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS collaboration_threads;
DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS case_technologies;
DROP TABLE IF EXISTS case_tags;
DROP TABLE IF EXISTS case_success_factors;
DROP TABLE IF EXISTS case_share_records;
DROP TABLE IF EXISTS case_reference_records;
DROP TABLE IF EXISTS case_lessons_learned;
DROP TABLE IF EXISTS case_highlights;
DROP TABLE IF EXISTS case_attachment_names;
DROP TABLE IF EXISTS calendar_events;
DROP TABLE IF EXISTS business_qualifications;
DROP TABLE IF EXISTS bid_result_sync_logs;
DROP TABLE IF EXISTS bid_result_reminders;
DROP TABLE IF EXISTS bid_result_fetch_results;
DROP TABLE IF EXISTS bar_site_verifications;
DROP TABLE IF EXISTS bar_site_sops;
DROP TABLE IF EXISTS bar_site_attachments;
DROP TABLE IF EXISTS bar_site_accounts;
DROP TABLE IF EXISTS bar_certificates;
DROP TABLE IF EXISTS bar_certificate_borrow_records;
DROP TABLE IF EXISTS bar_assets;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS assembly_templates;
DROP TABLE IF EXISTS approval_requests;
DROP TABLE IF EXISTS approval_actions;
DROP TABLE IF EXISTS alert_rules;
DROP TABLE IF EXISTS alert_history;
DROP TABLE IF EXISTS ai_analysis_results;
DROP TABLE IF EXISTS ai_analysis_jobs;
DROP TABLE IF EXISTS accounts;
-- Manual rollback required for statement: future changes belong in db/migration-mysql. set names utf8mb4
