<template>
  <el-aside width="320px" class="right-sidebar" aria-label="项目辅助信息">
    <el-card v-if="ctx.showAICheckCard" class="ai-check-card"><template #header><div class="card-title"><el-icon><MagicStick /></el-icon><span>AI智能检查</span><el-button v-if="ctx.canRunAICheck" type="primary" size="small" @click="ctx.runAICheck" :loading="ctx.aiChecking"><el-icon v-if="!ctx.aiChecking"><VideoPlay /></el-icon>{{ ctx.aiChecking ? '检查中...' : '开始检查' }}</el-button></div></template><el-tabs v-model="ctx.activeAITab" class="ai-tabs"><el-tab-pane name="compliance"><template #label><div class="tab-label"><span>合规性检查</span><el-badge v-if="ctx.aiResult.compliance" :value="ctx.aiResult.compliance.score" :type="ctx.getBadgeType(ctx.aiResult.compliance.score)" :max="100" /></div></template><div class="check-result"><div class="score-section"><el-progress type="circle" :percentage="Number(ctx.aiResult.compliance?.score || 0)" :color="ctx.getProgressColor(ctx.aiResult.compliance?.score || 0)" :width="100"><template #default="{ percentage }"><span class="score-text">{{ ctx.formatScore(percentage) }}分</span></template></el-progress><p class="score-level">{{ ctx.getScoreLevel(ctx.aiResult.compliance?.score || 0) }}</p></div><el-empty description="点击开始检查进行AI分析" :image-size="80" /></div></el-tab-pane><el-tab-pane name="score"><template #label><div class="tab-label"><span>智能评分</span><el-badge v-if="ctx.aiResult.score" :value="ctx.aiResult.score.total || 0" type="primary" /></div></template><div class="ai-score"><div class="score-header"><h4>AI模拟专家评审</h4><el-tag :type="ctx.getOverallScoreType(ctx.aiResult.score?.total || 0)" size="large">综合评分: {{ ctx.aiResult.score?.total || 0 }}分</el-tag></div><el-empty v-if="!ctx.aiResult.score" description="点击开始检查进行AI智能评分" :image-size="80" /></div></el-tab-pane></el-tabs></el-card>
    <el-card class="action-card"><template #header><div class="card-title"><el-icon><Operation /></el-icon><span>快捷操作</span></div></template><div class="action-list"><el-button v-if="ctx.canManageProjectDocuments" :icon="DocumentAdd" @click="ctx.handleAddDocument">添加文档</el-button><el-button :icon="Share" @click="ctx.handleShare">分享项目</el-button><el-button :icon="Download" @click="ctx.handleExport">导出资料</el-button><el-button v-if="ctx.canSetProjectReminder" :icon="Bell" @click="ctx.handleSetReminder">设置提醒</el-button></div></el-card>
    <el-card class="timeline-card"><template #header><div class="card-title"><el-icon><Clock /></el-icon><span>项目动态</span></div></template><el-timeline><el-timeline-item v-for="activity in ctx.activities" :key="activity.id" :timestamp="activity.time" placement="top"><div class="activity-content"><span class="activity-user">{{ activity.user }}</span><span class="activity-action">{{ activity.action }}</span></div></el-timeline-item></el-timeline></el-card>
  </el-aside>
</template>

<script setup>
import { Bell, Clock, DocumentAdd, Download, MagicStick, Operation, Share, VideoPlay } from '@element-plus/icons-vue'
import { useProjectDetailContext } from '@/composables/projectDetail/context.js'

const ctx = useProjectDetailContext()
</script>
